services:
  haroun.dev:
    container_name: haroun.dev
    restart: unless-stopped
    image: haroun.dev
    ports:
      - 80:80
    build: .
  bonita:
    image: bonita:2024.3
    ports:
      - 8080:8080